### PR TITLE
regenerate style.css

### PR DESCRIPTION
**Pull request by jokin**
Import the css so rollup can get the reference to the scss file and generate the styles on build.

### CODE REVIEW

**Comment by antony** [comment]
This would mean that everybody gets the same style.css - which is not the intention.

**Comment by jokin** [comment]
What's the development workflow then? Manually regenerate the style.css from scss whenever you made changes to sytle.scss?

**Comment by antony** [comment]
The seperate style css was created as a PR so I don't know the intended flow, but, what development flow are you looking for? Building this library itself, or building it as part of another project? Or something else?

**Comment by antony** [comment]
Closing due to inactivity

**Pull request closed without merging**
